---
title: "Project Draft"
author: "Haley Vien"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
library(fivethirtyeight)
library(ggplot2)
data("hiphop_cand_lyrics")
library(broom)
library(moderndive)
library(tidyverse)
library(openintro)
library(ggridges)
```

#Research Question

```{r}
hiphop_hcdt <- hiphop_cand_lyrics %>% 
  filter(candidate %in% c("Hillary Clinton", "Donald Trump"))
```

```{r}
hiphop_hc <- hiphop_cand_lyrics %>% 
  filter(candidate %in% c("Hillary Clinton"))
```

```{r}
hiphop_dt <- hiphop_cand_lyrics %>% 
  filter(candidate %in% c("Donald Trump"))
```

When looking at Hillary and Trump’s mentions in hip hop songs, does the relation between theme and sentiment differ between the two and does that change over time?

Our response variable is sentiment while our explanatory variable is theme. 

```{r}
ggplot(data = hiphop_hcdt) + 
  geom_bar(aes(x = sentiment, fill = theme)) +
  facet_wrap(vars(candidate))
```

```{r}
ggplot(data = hiphop_hcdt)+
   geom_density_ridges(aes(x = album_release_date, fill = candidate, y = sentiment), alpha = .5)

```

```{r}
glm.cand <- glm(factor(sentiment) ~ candidate,
            data = hiphop_hcdt,
           family = binomial(link = "logit"))

tidy(glm.cand)
```


```{r}
glm.cand.date <- glm(factor(sentiment) ~ candidate + album_release_date,
            data = hiphop_hcdt,
           family = binomial(link = "logit"))

tidy(glm.cand.date)
```

